# Generated by Django 5.0.2 on 2025-02-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_vulnerability_notes_vulnerability_cve_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('id_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('life_test_result', models.CharField(max_length=50)),
                ('document_check_result', models.CharField(max_length=50)),
                ('facematch_result', models.CharField(max_length=50)),
                ('biometric_result', models.CharField(max_length=50)),
            ],
        ),
    ]
